language: php
php:
  - 7.4
  - 7.3
  - 7.2

before_script:
    - composer install

script:
    - phpunit --configuration tests/phpunit.xml

notifications:
  recipients:
    - david.gorges@leaphub.de
  on_success: change
  on_failure: always
